FROM node:10-alpine AS build
WORKDIR /ladno
COPY . .
RUN npm install && npm run build

FROM nginx:stable-alpine AS serve
COPY --from=build /ladno/dist /usr/share/nginx/html
COPY docker/nginx.default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
